import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([4,5,6,7,8])
z= np.subtract(x,y)
print('this is subtraction')
print(z)
z= np.multiply(x,y)
print('this is multiplication')
print(z)
z= np.divide(x,y)
print('this is division')
print(z)
z= np.power(x,y)
print('this is power')
print(z)
x=np.array([10,2,3,4,5,6])
y=np.array([4,5,6,5,7,8])
z=np.mod(x,y)
print('this is modulus')
print(z)
x= np.array([10,1,2,3,45,5])
y = np.array([7,8,9,45,6,3])
z= np.divmod(x,y)
print()
print(z)

# similarly try for aboslout command i.e. np.aboslute(arr)

